import type {
  AgentModuleMeta,
  ApiPoolMode,
  CoreServiceMeta,
  TopologyMode,
  WorkflowTargetMeta,
} from './types'

export const NOVEL_TYPES = [
  '玄幻',
  '仙侠',
  '都市',
  '言情',
  '悬疑',
  '历史',
  '科幻',
  '武侠',
  '无限流',
  '爽文',
  '系统文',
  '重生文',
  '穿越文',
  '发疯文学',
  '灵异',
  '总裁文',
  '赛博朋克',
  '脑洞',
] as const

export const TOPOLOGY_OPTIONS: Array<{ label: string; value: TopologyMode }> = [
  { label: '自动检测', value: 'auto' },
  { label: '线性串行', value: 'linear' },
  { label: '三角协同', value: 'triangular' },
  { label: '专家蜂群', value: 'swarm' },
]

export const API_POOL_OPTIONS: Array<{ label: string; value: ApiPoolMode }> = [
  { label: '自动', value: 'auto' },
  { label: '单模型', value: 'single' },
  { label: '三模型', value: 'triple' },
  { label: '蜂群', value: 'swarm' },
]

export const WORKFLOW_TARGETS: WorkflowTargetMeta[] = [
  {
    id: 'opening',
    label: '开篇场景',
    description: 'OpeningSceneGenerator 生成带节奏的开篇段落',
    module: 'OpeningSceneGenerator',
    file: 'tools/opening_scene_generator.py',
    flow: 'creation',
    outputKey: 'opening',
  },
  {
    id: 'titles',
    label: '章节/书名',
    description: 'ChapterTitleGenerator 输出章节候选与命名理由',
    module: 'ChapterTitleGenerator',
    file: 'tools/chapter_title_generator.py',
    flow: 'creation',
    outputKey: 'chapterTitles',
  },
  {
    id: 'commercial',
    label: '商业包装',
    description: 'CommercialOptimizer 生成卖点与宣发要点',
    module: 'CommercialOptimizer',
    file: 'tools/commercial_optimizer.py',
    flow: 'creation',
    outputKey: 'commercial',
  },
  {
    id: 'platform',
    label: '平台适配',
    description: 'PlatformAdapter 输出番茄/起点等平台建议',
    module: 'PlatformAdapter',
    file: 'tools/platform_adapter.py',
    flow: 'creation',
    outputKey: 'platformAdaptation',
  },
  {
    id: 'emotion',
    label: '情绪节拍',
    description: 'EmotionCurveOptimizer 绘制章节情绪曲线',
    module: 'EmotionCurveOptimizer',
    file: 'tools/emotion_curve_optimizer.py',
    flow: 'optimization',
    outputKey: 'emotionDashboard',
  },
  {
    id: 'hook',
    label: '钩子诊断',
    description: 'HookOptimizer 评估章节钩子与反转',
    module: 'HookOptimizer',
    file: 'tools/hook_optimizer.py',
    flow: 'creation',
    outputKey: 'hookDiagnostics',
  },
  {
    id: 'characters',
    label: '人物一致性',
    description: 'CharacterConsistencyChecker 校准人物设定/口癖',
    module: 'CharacterConsistencyChecker',
    file: 'tools/character_consistency_checker.py',
    flow: 'optimization',
    outputKey: 'characterIssues',
  },
  {
    id: 'foreshadowing',
    label: '伏笔追踪',
    description: 'ForeshadowingReminder 生成伏笔提醒与排期',
    module: 'ForeshadowingReminder',
    file: 'tools/foreshadowing_reminder.py',
    flow: 'optimization',
    outputKey: 'foreshadowingReport',
  },
  {
    id: 'ending',
    label: '结局设计',
    description: 'EndingOptimizer 输出多版本结局提案',
    module: 'EndingOptimizer',
    file: 'tools/ending_optimizer.py',
    flow: 'optimization',
    outputKey: 'endingAnalysis',
  },
  {
    id: 'worldview',
    label: '世界观冲突',
    description: 'WorldviewConflictDetector 标记设定矛盾',
    module: 'WorldviewConflictDetector',
    file: 'tools/worldview_conflict_detector.py',
    flow: 'optimization',
    outputKey: 'worldviewConflicts',
  },
  {
    id: 'aiEvasion',
    label: 'AI检测规避',
    description: 'AIDetectionEvader 评估命中率并生成规避策略',
    module: 'AIDetectionEvader',
    file: 'tools/ai_detection_evader.py',
    flow: 'detection',
    outputKey: 'detectionFlow',
  },
  {
    id: 'villain',
    label: '反派建模',
    description: 'VillainCreator 构建多维反派画像（后端预研中）',
    module: 'VillainCreator',
    file: 'tools/villain_creator.py',
    flow: 'optimization',
    outputKey: 'villainBlueprint',
    disabled: true,
  },
] as const

export const AGENT_MODULES: AgentModuleMeta[] = [
  {
    id: 'reader',
    label: 'Reader · 分块',
    description: '负责原始文本分段与语义 chunk 化',
    file: 'agents/reader.py',
  },
  {
    id: 'scanner',
    label: 'Scanner · 语义预检',
    description: '执行轻量质检，筛除噪点/特殊格式',
    file: 'agents/scanner.py',
  },
  {
    id: 'extractor',
    label: 'Extractor · 事实抽取',
    description: '结合 Frankentexts 检索抽取实体与线索',
    file: 'agents/extractor.py',
  },
  {
    id: 'analyst',
    label: 'Analyst · 深度剖析',
    description: 'LLM 分析人物、冲突与世界观',
    file: 'agents/analyst.py',
  },
  {
    id: 'planner',
    label: 'Planner · 剧情规划',
    description: '生成故事结构与章节大纲',
    file: 'agents/planner.py',
  },
  {
    id: 'archivist',
    label: 'Archivist · 记忆体',
    description: '写入 YAML 记忆体与伏笔档案',
    file: 'agents/archivist.py',
  },
  {
    id: 'stylist',
    label: 'Stylist · 文风增强',
    description: '统一叙事语气并平衡节奏',
    file: 'agents/stylist.py',
  },
  {
    id: 'creative',
    label: 'Creative Workflow · 工具编排',
    description: '调度 10+ 创作工具的高级流程',
    file: 'core/creative_workflow.py',
  },
]

export const CORE_SERVICES: CoreServiceMeta[] = [
  {
    id: 'topology',
    label: 'TopologyManager',
    description: '根据 API 资源切换 linear / triangular / swarm',
    file: 'core/topology_manager.py',
    valueKey: 'topologyMode',
  },
  {
    id: 'api',
    label: 'APIOptimizer / EnhancedLLMClient',
    description: '多 API 池智能调度与模型路由',
    file: 'core/api_optimizer.py',
    valueKey: 'apiPoolMode',
  },
  {
    id: 'memory',
    label: 'MemoryManager',
    description: '管理 YAML 记忆体与输出目录',
    file: 'core/memory_manager.py',
  },
  {
    id: 'frankentexts',
    label: 'FrankentextsManager',
    description: '向量召回典型场景，辅助提取',
    file: 'core/frankentexts.py',
  },
  {
    id: 'genre',
    label: 'GenreEnhancer',
    description: '根据类型标签注入题材特征',
    file: 'core/genre_enhancer.py',
  },
  {
    id: 'workflow',
    label: 'CreativeWorkflowPipeline',
    description: '统一 orchestrator，衔接 creation/optimization/detection',
    file: 'core/creative_workflow.py',
  },
]

